# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\"\x1d\n\rChangeRequest\x12\x0c\n\x04json\x18\x02 \x01(\t\"\x1e\n\x0b\x43hangeReply\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x08\x45xecutor\x12-\n\x0b\x41pplyChange\x12\x0e.ChangeRequest\x1a\x0c.ChangeReply\"\x00\x62\x06proto3'
)




_CHANGEREQUEST = _descriptor.Descriptor(
  name='ChangeRequest',
  full_name='ChangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='ChangeRequest.json', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=46,
)


_CHANGEREPLY = _descriptor.Descriptor(
  name='ChangeReply',
  full_name='ChangeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ChangeReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['ChangeRequest'] = _CHANGEREQUEST
DESCRIPTOR.message_types_by_name['ChangeReply'] = _CHANGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangeRequest = _reflection.GeneratedProtocolMessageType('ChangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ChangeRequest)
  })
_sym_db.RegisterMessage(ChangeRequest)

ChangeReply = _reflection.GeneratedProtocolMessageType('ChangeReply', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEREPLY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ChangeReply)
  })
_sym_db.RegisterMessage(ChangeReply)



_EXECUTOR = _descriptor.ServiceDescriptor(
  name='Executor',
  full_name='Executor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=80,
  serialized_end=137,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApplyChange',
    full_name='Executor.ApplyChange',
    index=0,
    containing_service=None,
    input_type=_CHANGEREQUEST,
    output_type=_CHANGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXECUTOR)

DESCRIPTOR.services_by_name['Executor'] = _EXECUTOR

# @@protoc_insertion_point(module_scope)
